data:
- children:
  - children:
    - children:
      - name: Voiced stops
        phones:
        - b
        - d
        - "\u025F"
        - g
        ref: <VoicedStop>
      name: voiced stops
      ref: <VoicedStop>
    - name: voiceless stops
      phones:
      - p
      - t
      - c
      - k
      ref: <VoicelessStop>
    name: stops
    ref: <Stop>
  - children:
    - name: voiced fricatives
      phones:
      - v
      - "\xF0"
      ref: <VoicedFrc>
    - name: voiceless fricative
      phones:
      - s
      ref: <VoicelessFrc>
    name: fricatives
    ref: <Frc>
  - children:
    - name: nasals
      phones:
      - m
      - n
      - "\u0272"
      - "\u014B"
      ref: <N>
    - name: liquids
      phones:
      - r
      - "\u027E"
      - "\u027D"
      - l
      ref: <Liq>
    - name: glides
      phones:
      - j
      - w
      ref: <Glide>
    name: sonorants
    ref: <Son>
  name: Consonants
  ref: <C>
- children:
  - name: high vowels
    phones:
    - i
    - u
    ref: <Vhi>
  - name: mid vowels
    phones:
    - e
    - o
    - "\u025B"
    - "\u025C"
    - "\u0254"
    ref: <Vmid>
  - name: low vowels
    phones:
    - a
    ref: <Vlo>
  - name: tone
    phones:
    - "\u0301"
    - "\u0300"
    - "\u0302"
    - "\u030C"
    ref: <T>
  name: vowels
  ref: <V>
kind: Inventory
